const fs = require('fs');
const path = require('path');

// List of trending searches (could be pulled from an API)
const trendingKeywords = [
  'Dow Jones stock markets',
  'hims stock',
  'blackrock',
  'gasbuddy',
  'tax refunds',
  'orcl stock',
  'nifty prediction',
  'petrol price kolkata',
  'wti',
  'stock market crash',
  'investment tips 2026',
  'fuel cost calculator',
];

function createBlogPost() {
  const date = new Date();
  const filename = `trending-${date.getFullYear()}${String(date.getMonth()+1).padStart(2,'0')}${String(date.getDate()).padStart(2,'0')}.md`;
  const filepath = path.join(__dirname, '../content/blog', filename);

  let content = `---
title: "Trending Search Insights: ${date.toDateString()}"
description: "A roundup of trending search terms and how our tools relate to them."
date: "${date.toISOString()}"
author: "Stravotech"
tags: [trending, seo, keywords]
---

# Trending Searches You Need to Know Today

Here's a curated list of today's hottest search topics on Google. We incorporate these keywords across our tools and articles to boost SEO and attract organic traffic. When users read this post, they'll find direct links to useful calculators and guides.

`;

  trendingKeywords.forEach(keyword => {
    content += `- **${keyword}** - check out our related tool or article: [Search now](#)
`;
  });

  content += `

Stay tuned for daily updates!\
_This post is automatically generated by a script that collects trending keywords and adds them to the Stravotech blog._
`;

  fs.writeFileSync(filepath, content, 'utf8');
  console.log(`Generated blog post at ${filepath}`);
}

createBlogPost();
